name: investania
description: A Skandia Hackathon 2023 game about saving money

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  build_runner: ^2.3.3
  collection: ^1.17.0
  flame:
    git:
      url: https://github.com/flame-engine/flame.git
      ref: main
      path: packages/flame
  flame_audio: ^1.4.0
  flame_riverpod: ^4.0.0+2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.1
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  intl: ^0.18.0
  riverpod_annotation: ^2.0.1

dependency_overrides:
  flame:
    git:
      url: https://github.com/flame-engine/flame.git
      ref: main
      path: packages/flame


dev_dependencies:
  flame_lint: ^0.2.0
  riverpod_generator: ^2.1.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/parallax/
    - assets/images/player/
    - assets/fonts/
    - assets/audio/

  fonts:
    - family: asap
      fonts:
        - asset: assets/fonts/Asap-Regular.ttf
        - asset: assets/fonts/Asap-Thin.ttf
          weight: 100
        - asset: assets/fonts/Asap-Light.ttf
          weight: 300
        - asset: assets/fonts/Asap-Medium.ttf
          weight: 500
        - asset: assets/fonts/Asap-Bold.ttf
          weight: 700
        - asset: assets/fonts/Asap-Italic.ttf
          style: italic
    
