name: investania
description: A Skandia Hackathon 2023 game about saving money

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  build_runner: ^2.4.6
  collection: ^1.17.1
  flame: ^1.8.1
  flame_audio: ^2.0.4
  flame_riverpod: ^4.0.0+2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  freezed: ^2.4.1
  freezed_annotation: ^2.4.1
  gamepads: ^0.1.1
  intl: ^0.18.1
  riverpod_annotation: ^2.1.1

dev_dependencies:
  flame_lint: ^1.0.0
  riverpod_generator: ^2.2.3


dependency_overrides:
  flame:
    git:
      url: https://github.com/lohnn/flame.git
      ref: fix/exception_hud_margin_component
      path: packages/flame

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/money/
    - assets/images/parallax/
    - assets/images/player/
    - assets/fonts/
    - assets/audio/

  fonts:
    - family: asap
      fonts:
        - asset: assets/fonts/Asap-Regular.ttf
        - asset: assets/fonts/Asap-Thin.ttf
          weight: 100
        - asset: assets/fonts/Asap-Light.ttf
          weight: 300
        - asset: assets/fonts/Asap-Medium.ttf
          weight: 500
        - asset: assets/fonts/Asap-Bold.ttf
          weight: 700
        - asset: assets/fonts/Asap-Italic.ttf
          style: italic
    
