name: investania
description: A Skandia Hackathon 2023 game about saving money

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  flame: ^1.6.0
  flame_riverpod: ^4.0.0+2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.1

dev_dependencies:
  flame_lint: ^0.2.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - asset: assets/fonts/Asap-Regular.ttf
    - asset: assets/fonts/Asap-Thin.ttf
      weight: 100
    - asset: assets/fonts/Asap-Light.ttf
      weight: 300
    - asset: assets/fonts/Asap-Medium.ttf
      weight: 500
    - asset: assets/fonts/Asap-Bold.ttf
      weight: 700
    - asset: assets/fonts/Asap-Italic.ttf
      style: italic
